spring:
  profiles:
    active: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: false
#    defer-datasource-initialization: true #임시추가
#
#  sql:
#    init:
#      mode: always #임시추가


